sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t radjablonski01/docker_nodejs_travisjs -f Dockerfile.dev .

script:
  - docker run radjablonski01/docker_nodejs_travisjs npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ""
  app: ""
  env: ""
  bucket_name: ""
  backet_path: ""
  on:
    branch: master